INSERT INTO cards (user_id, set_id, word, translation, transcription, created_at, updated_at)
VALUES
    (2, 6, 'go', 'идти', NULL, NOW(), NOW()),
    (2, 6, 'travel', 'ехать', NULL, NOW(), NOW()),
    (2, 6, 'stand', 'стоять', NULL, NOW(), NOW()),
    (2, 6, 'jump', 'прыгать', NULL, NOW(), NOW()),
    (2, 6, 'think', 'думать', NULL, NOW(), NOW()),
    (2, 6, 'walk', 'ходить', NULL, NOW(), NOW()),
    (2, 6, 'go in', 'заходить', NULL, NOW(), NOW()),
    (2, 6, 'go out', 'выходить', NULL, NOW(), NOW()),
    (2, 6, 'clap', 'хлопать', NULL, NOW(), NOW()),
    (2, 6, 'whistle', 'свистеть', NULL, NOW(), NOW()),
    (2, 6, 'scream', 'кричать', NULL, NOW(), NOW()),
    (2, 6, 'cook', 'готовить', NULL, NOW(), NOW()),
    (2, 6, 'write', 'писать', NULL, NOW(), NOW()),
    (2, 6, 'read', 'читать', NULL, NOW(), NOW()),
    (2, 6, 'speak', 'говорить', NULL, NOW(), NOW()),
    (2, 6, 'persuade', 'уговаривать', NULL, NOW(), NOW()),
    (2, 6, 'ask', 'спрашивать, просить', NULL, NOW(), NOW()),
    (2, 6, 'respond', 'отвечать', NULL, NOW(), NOW()),
    (2, 6, 'deny', 'отказывать', NULL, NOW(), NOW()),
    (2, 6, 'raise', 'поднимать', NULL, NOW(), NOW()),
    (2, 6, 'lower', 'опускать', NULL, NOW(), NOW()),
    (2, 6, 'paint', 'красить', NULL, NOW(), NOW()),
    (2, 6, 'wash', 'стирать, мыть', NULL, NOW(), NOW()),
    (2, 6, 'draw', 'рисовать, чертить', NULL, NOW(), NOW()),
    (2, 6, 'put', 'класть', NULL, NOW(), NOW()),
    (2, 6, 'touch', 'трогать', NULL, NOW(), NOW()),
    (2, 6, 'throw out', 'выбрасывать', NULL, NOW(), NOW()),
    (2, 6, 'throw', 'бросать, кидать', NULL, NOW(), NOW()),
    (2, 6, 'repair', 'ремонтировать', NULL, NOW(), NOW()),
    (2, 6, 'move', 'переезжать', NULL, NOW(), NOW()),
    (2, 6, 'wear', 'носить', NULL, NOW(), NOW()),
    (2, 6, 'twist', 'крутить', NULL, NOW(), NOW()),
    (2, 6, 'learn', 'учить', NULL, NOW(), NOW()),
    (2, 6, 'work', 'работать', NULL, NOW(), NOW()),
    (2, 6, 'build', 'строить', NULL, NOW(), NOW()),
    (2, 6, 'educate', 'воспитывать', NULL, NOW(), NOW()),
    (2, 6, 'give birth', 'рожать', NULL, NOW(), NOW()),
    (2, 6, 'start', 'заводить', NULL, NOW(), NOW()),
    (2, 6, 'begin', 'начинать', NULL, NOW(), NOW()),
    (2, 6, 'finish', 'заканчивать', NULL, NOW(), NOW()),
    (2, 6, 'leave', 'покидать, оставить', NULL, NOW(), NOW()),
    (2, 6, 'boil', 'варить', NULL, NOW(), NOW()),
    (2, 6, 'fry', 'жарить', NULL, NOW(), NOW()),
    (2, 6, 'sing', 'петь', NULL, NOW(), NOW()),
    (2, 6, 'dance', 'танцевать', NULL, NOW(), NOW()),
    (2, 6, 'feed', 'кормить', NULL, NOW(), NOW()),
    (2, 6, 'score', 'забивать', NULL, NOW(), NOW()),
    (2, 6, 'swim', 'плавать', NULL, NOW(), NOW()),
    (2, 6, 'fly', 'летать', NULL, NOW(), NOW()),
    (2, 6, 'crawl', 'ползать', NULL, NOW(), NOW()),
    (2, 6, 'spoil', 'портить', NULL, NOW(), NOW()),
    (2, 6, 'help', 'помогать', NULL, NOW(), NOW()),
    (2, 6, 'drip', 'капать', NULL, NOW(), NOW()),
    (2, 6, 'treat', 'лечить', NULL, NOW(), NOW()),
    (2, 6, 'stroke', 'гладить', NULL, NOW(), NOW()),
    (2, 6, 'bite', 'кусать', NULL, NOW(), NOW()),
    (2, 6, 'eat', 'есть', NULL, NOW(), NOW()),
    (2, 6, 'drink', 'пить', NULL, NOW(), NOW()),
    (2, 6, 'threaten', 'угрожать', NULL, NOW(), NOW()),
    (2, 6, 'find', 'найти, находить', NULL, NOW(), NOW()),
    (2, 6, 'win', 'выиграть', NULL, NOW(), NOW()),
    (2, 6, 'lose', 'проиграть', NULL, NOW(), NOW()),
    (2, 6, 'choose', 'выбрать', NULL, NOW(), NOW()),
    (2, 6, 'take', 'взять', NULL, NOW(), NOW()),
    (2, 6, 'give', 'дать', NULL, NOW(), NOW()),
    (2, 6, 'pray', 'молиться', NULL, NOW(), NOW()),
    (2, 6, 'apply', 'ходатайствовать', NULL, NOW(), NOW()),
    (2, 6, 'beg', 'умолять', NULL, NOW(), NOW()),
    (2, 6, 'look for', 'искать', NULL, NOW(), NOW()),
    (2, 6, 'charge', 'заряжать', NULL, NOW(), NOW()),
    (2, 6, 'show', 'предъявлять', NULL, NOW(), NOW()),
    (2, 6, 'demand', 'требовать', NULL, NOW(), NOW()),
    (2, 6, 'try', 'пытаться', NULL, NOW(), NOW()),
    (2, 6, 'communicate', 'общаться', NULL, NOW(), NOW()),
    (2, 6, 'participate', 'участвовать', NULL, NOW(), NOW());
