-- Шаблонные наборы карточек (стандартные топики для новых пользователей)
-- IDENTITY совместим с PostgreSQL и H2
CREATE TABLE template_sets (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL UNIQUE,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE template_cards (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_set_id BIGINT NOT NULL REFERENCES template_sets(id) ON DELETE CASCADE,
    word            VARCHAR(500) NOT NULL,
    translation     VARCHAR(500) NOT NULL,
    transcription   VARCHAR(500)
);

CREATE INDEX idx_template_cards_set_id ON template_cards(template_set_id);

-- Данные: 8 топиков по 10 слов
INSERT INTO template_sets (name, sort_order) VALUES
    ('Животные', 1),
    ('Еда и напитки', 2),
    ('Семья', 3),
    ('Дом', 4),
    ('Цвета', 5),
    ('Путешествия', 6),
    ('Работа', 7),
    ('Природа', 8);

INSERT INTO template_cards (template_set_id, word, translation, transcription) VALUES
-- Животные (id=1)
(1, 'dog', 'собака', NULL),
(1, 'cat', 'кошка', NULL),
(1, 'bird', 'птица', NULL),
(1, 'fish', 'рыба', NULL),
(1, 'horse', 'лошадь', NULL),
(1, 'cow', 'корова', NULL),
(1, 'pig', 'свинья', NULL),
(1, 'mouse', 'мышь', NULL),
(1, 'rabbit', 'кролик', NULL),
(1, 'bear', 'медведь', NULL),
-- Еда и напитки (id=2)
(2, 'apple', 'яблоко', 'ˈæpl'),
(2, 'bread', 'хлеб', NULL),
(2, 'milk', 'молоко', NULL),
(2, 'water', 'вода', NULL),
(2, 'coffee', 'кофе', NULL),
(2, 'tea', 'чай', NULL),
(2, 'meat', 'мясо', NULL),
(2, 'vegetables', 'овощи', NULL),
(2, 'fruit', 'фрукты', NULL),
(2, 'breakfast', 'завтрак', NULL),
-- Семья (id=3)
(3, 'mother', 'мама', NULL),
(3, 'father', 'папа', NULL),
(3, 'brother', 'брат', NULL),
(3, 'sister', 'сестра', NULL),
(3, 'family', 'семья', NULL),
(3, 'child', 'ребёнок', NULL),
(3, 'parents', 'родители', NULL),
(3, 'grandmother', 'бабушка', NULL),
(3, 'grandfather', 'дедушка', NULL),
(3, 'friend', 'друг', NULL),
-- Дом (id=4)
(4, 'house', 'дом', NULL),
(4, 'room', 'комната', NULL),
(4, 'door', 'дверь', NULL),
(4, 'window', 'окно', NULL),
(4, 'table', 'стол', NULL),
(4, 'chair', 'стул', NULL),
(4, 'bed', 'кровать', NULL),
(4, 'kitchen', 'кухня', NULL),
(4, 'bathroom', 'ванная', NULL),
(4, 'garden', 'сад', NULL),
-- Цвета (id=5)
(5, 'red', 'красный', NULL),
(5, 'blue', 'синий', NULL),
(5, 'green', 'зелёный', NULL),
(5, 'yellow', 'жёлтый', NULL),
(5, 'black', 'чёрный', NULL),
(5, 'white', 'белый', NULL),
(5, 'orange', 'оранжевый', NULL),
(5, 'brown', 'коричневый', NULL),
(5, 'grey', 'серый', NULL),
(5, 'pink', 'розовый', NULL),
-- Путешествия (id=6)
(6, 'travel', 'путешествовать', NULL),
(6, 'trip', 'поездка', NULL),
(6, 'airport', 'аэропорт', NULL),
(6, 'hotel', 'отель', NULL),
(6, 'passport', 'паспорт', NULL),
(6, 'ticket', 'билет', NULL),
(6, 'luggage', 'багаж', NULL),
(6, 'map', 'карта', NULL),
(6, 'beach', 'пляж', NULL),
(6, 'city', 'город', NULL),
-- Работа (id=7)
(7, 'work', 'работа', NULL),
(7, 'office', 'офис', NULL),
(7, 'meeting', 'встреча', NULL),
(7, 'computer', 'компьютер', NULL),
(7, 'phone', 'телефон', NULL),
(7, 'email', 'электронная почта', NULL),
(7, 'boss', 'начальник', NULL),
(7, 'colleague', 'коллега', NULL),
(7, 'salary', 'зарплата', NULL),
(7, 'project', 'проект', NULL),
-- Природа (id=8)
(8, 'sun', 'солнце', NULL),
(8, 'moon', 'луна', NULL),
(8, 'tree', 'дерево', NULL),
(8, 'flower', 'цветок', NULL),
(8, 'river', 'река', NULL),
(8, 'mountain', 'гора', NULL),
(8, 'sky', 'небо', NULL),
(8, 'rain', 'дождь', NULL),
(8, 'snow', 'снег', NULL),
(8, 'wind', 'ветер', NULL);
